### ISSUE TITLE
'Git Builds' Workflow not always Producing a New Build when Merging to Main

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#1079]
# Bug Report

## Summary

https://github.com/Nexus-Mods/NexusMods.App/actions/workflows/git-builds.yaml

![20240318_16h49m33s](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/3c05a99e-fbcb-4602-ac75-77160cbd777b)

The 'Git Builds' Action is not always being triggered after PRs are merged to main.

## Steps to reproduce

<Unknown, Not Investigated>

## What is the expected behaviour?

A build should be made after every change makes it to the 'Main' branch.

## Other

[git-builds.yaml](https://github.com/Nexus-Mods/NexusMods.App/blob/main/.github/workflows/git-builds.yaml) has the following
```
on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/clean_environment_tests.yaml"
      - "./src/**"
      - "./tests/**"
      - "**.props"
      - "**.targets"
```

[clean-environment-tests.yaml](https://github.com/Nexus-Mods/NexusMods.App/blob/main/.github/workflows/clean_environment_tests.yaml) has the following
```
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/clean_environment_tests.yaml"
      - "src/**"
      - "tests/**"
      - "**.props"
      - "**.targets"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/clean_environment_tests.yaml"
      - "src/**"
      - "tests/**"
      - "**.props"
      - "**.targets"
    types: [ opened, synchronize, reopened, ready_for_review ]
```

The latter appears to work fine, the former not.
It may be due to `./` prefix in the former, but I haven't yet confirmed.
