### ISSUE TITLE
Add sorting support for mods

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#18]
Currently mods are sorted by hash value, which is completely useless. We need to implement a way of sorting mods. Since our current storage of mods in a loadout is simply a hashset of mods, it seems like a simple way would to implement this would be via set of rules. Rules that we would certainly need

* Load First (use by the game files)
* Loads After
* Loads Before

Starting with these we should be able to implement some fairly complex loadouts. In order to have mods refer to eachother in a generic way, we'll need to create a `ModId` for each mod and then implement a polymorphic set of loading rules for each mod. 

The data structure could probably be:

```yaml
- Loadout
  Mods:
    - Name: GameFiles
      Id: 44242
      SortRules:
        - Load First
    - Name: MyMod
      Id: 44243
      SortRules:
        - Load After: 44242 
    - Name: MyMod2
      Id: 44244
      SortRules:
        - Load Before: 44244
```

After this is implemented, we'll need a simple DAG sorter, and then we can hook that into the flatten routine in the LoadOrder.
