### ISSUE TITLE
Flatpak release

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#2436]
Docs: https://docs.flatpak.org/en/latest/building.html

Needs investigating:
- Use of desktop portals (#1676)
- Flatpak permissions
- Pupnet support for publishing Flatpaks
- Validation of [`com.nexusmods.app.metainfo.xml`](https://github.com/Nexus-Mods/NexusMods.App/blob/main/src/NexusMods.App/com.nexusmods.app.metainfo.xml)
- Ownership of `com.nexusmods.app` ID on Flathub

**Comment by erri120** [comment]
Example `com.nexusmods.app.yaml` build file:

```yaml
id: com.nexusmods.app
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.dotnet9
build-options:
  prepend-path: "/usr/lib/sdk/dotnet9/bin"
  append-ld-library-path: "/usr/lib/sdk/dotnet9/lib"
  prepend-pkg-config-path: "/usr/lib/sdk/dotnet9/lib/pkgconfig"

command: "NexusMods.App"

finish-args:
  - --device=dri          # rendering
  - --device=input        # inputs, specifically controllers
  - --socket=x11          # windowing
  - --share=ipc           # for X11 shared memory extension
  - --share=network       # network
  - --socket=session-bus  # D-Bus
  - --env=DOTNET_ROOT=/app/lib/dotnet

modules:
  - name: dotnet
    buildsystem: simple
    build-commands:
    - /usr/lib/sdk/dotnet9/bin/install.sh

  - name: app
    buildsystem: simple
    build-options:
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'
    sources:
      - type: git
        url: "https://github.com/Nexus-Mods/NexusMods.App.git"
        tag: "main"
      - ./nuget-sources.json
    build-commands:
      - dotnet publish -r linux-x64 src/NexusMods.App/NexusMods.App.csproj --no-self-contained --source ./nuget-sources
      - mkdir -p ${FLATPAK_DEST}/bin
      - cp -r src/NexusMods.App/bin/Release/net9.0/linux-x64/publish/* ${FLATPAK_DEST}/bin
```

The `nuget-sources.json` file has to be generated with the [`flatpak-dotnet-generator.py`](https://github.com/flatpak/flatpak-builder-tools/blob/master/dotnet/flatpak-dotnet-generator.py) like this:

```bash
python3 flatpak-dotnet-generator.py --dotnet 9 --freedesktop 24.08 nuget-sources.json src/NexusMods.App/NexusMods.App.csproj
```

Then you can create the flatpak:

```bash
flatpak-builder build-dir --user --force-clean --install --repo=repo com.nexusmods.app.yaml
```

This is similar to a docker builder, the flatpack builder will create a flatpak with the SDK and run the build commands inside the builder.
