### ISSUE TITLE
GitHub bot for change tracking of games and important mods

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#269]
To better deal with game support issues arising from mods or games that got updated, it might be worth looking into adding a custom GitHub bot that runs periodically and checks for changes. If it finds any changes, it opens an issue with correct tags and assignees.

The bot would read from a config file (YAML) which contains a list of things to check for:

```yaml
config:
  cron: "0 10 * * MON-THU"
  games:
    labels: [ "game support", "automated" ]
  mods:
    labels: [ "automated" ]

games:
  - name: "Skyrim Special Edition"
  - name: "Stardew Valley"
    assignees: [ erri120 ]

mods:
  - name: "SMAPI"
    game: "Stardew Valley"
    github: "Pathoschild/SMAPI"
  - name: "redscript"
    game: "Cyberpunk 2077"
    nexus: 1511
    assignees: [ halgari ]
```
